service:
  name: slack-event-handler

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10
  region: ap-northeast-1

functions:
  handler:
    handler: src/handler.handler
    events:
      - http:
          method: post
          path: handler
